spring :
  application :
    name : apigateway
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: ${USER_SERVICE}
          predicates:
            - Path=/users/**,/payment-cards/**
        - id: auth-route
          uri: ${AUTH_SERVICE}
          predicates:
            - Path=/auth/**
        - id: order-route
          uri: ${ORDER_SERVICE}
          predicates:
            - Path=/orders/**,/items/**
server :
  port : 8083
services:
  auth:
    url: ${AUTH_SERVICE:http://localhost:8081}
  user:
    url: ${USER_SERVICE:http://localhost:8080}
internal:
  secret: ${SERVICE_SECRET}
logging:
  level:
    root: info
    com.innowise.apigateway: debug
  file:
    name: logs/apigateway.log
resilience4j:
  ratelimiter:
    instances:
      loginRateLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 5s
        timeoutDuration: 0ms
      registrationRateLimiter:
        limitForPeriod: 3
        limitRefreshPeriod: 1s
        timeoutDuration: 0ms
  circuitbreaker:
    instances:
      registrationCircuit:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        ignore-exceptions:
          - com.innowise.apigateway.exception.DeactivatedUserException
      loginCircuit:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        ignore-exceptions:
          - com.innowise.apigateway.exception.DeactivatedUserException