apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DB_PASSWORD: "cG9zdGdyZXM="
  JWT_SECRET: "ckZKNW1ZazJZY1B6NncwUXZWMkoBczN2UTBqOFh6cVZkMXY3Y1pwOHhRPQ=="
  SERVICE_SECRET: "c2VjcmV0"
  MONGODB_URL: "bW9uZ29kYjovL21vbmdvZGI6MjcwMTcvcGF5bWVudHNlcnZpY2VkYg=="